spring.application.name=staj-proje
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.jpa.properties.hibernate.default_schema=jforce_db
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

app.jwt.secret=5N+6yAw9UJlZGIE3ivXxkQlxnb9BauSkvcdSJ447DQE=
app.jwt.expiration-ms=7200000
